### ISSUE TITLE
Reconsider the Unlicense

### ISSUE THREAD

**Issue by jwodder** [zyansheep/rustyline-async#28]
`rustyline-async` is currently licensed under the Unlicense, [which has a number of problems as a license](https://chrismorgan.info/blog/unlicense/), not least being invalid under German law.  The project should consider switching to a better-drafted license, such as [0BSD](https://opensource.org/license/0bsd/).

However — and this is **very important** — because multiple people have contributed code to `rustyline-async` and one or more of them did so without assenting to a contributor license agreement, the copyright for `rustyline-async` is currently held by multiple people, all of whom must assent in order for the license to be changed.

**Comment by zyansheep** [comment]
I hear you, and I think I understand the criticisms (I remember doing a whole bunch of research awhile back on the difference between public domain dedication "licenses" and copyright-free licenses). Here's my take:

While the name may be misleading in some contexts, I think that's more an issue with popularity than anything else. The Unlicense is used widely, and is here to stay, thus anyone who is confused, but willing to figure out what the file called "Unlicense" means can learn with a quick search.

As to "being invalid under German law", there is the aspect that German law forbids in some sense "dedication to the public domain" (even by the author themselves). However, the Unlicense has a fallback clause for this exact purpose where it acts like a regular license (such as 0BSD) in such jurisdictions. Reading through the mailing list there is some controversy as to whether this fallback clause is indeed a fallback clause and will work in practice, however from my gatherings, the conclusion on the mailing list was that in practice, no court is going to interpret it for anything other than what it is.
https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-May/004858.html
https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-May/004870.html

Also: the link on the stackexchange post doesn't have context so here is the correct link: https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2012-January/001386.html. If you are interested in the responses.

On the topic of replacing with 0BSD, Here's a [YC comment](https://news.ycombinator.com/item?id=30556806) detailing the issue with 0BSD (tldr: it doesn't contain a public domain dedication). A license like CC0 would be okay, but it is not strictly a software license, and generally not as popular (I think) compared to the Unlicense. (Also, not approved by the OSI for some reason, and not a default GitHub option)

Here's my final take though. The reasons I chose (and will likely continue to choose) the Unlicense are ideological. I dislike the idea of copyright (I understand why it exists, but I think as it currently stands, it is outdated, ineffective and due for [a replacement](https://www.youtube.com/watch?v=jIM6dN3ogbk)). The Unlicense to me, is a bit like an ideological statement toward this goal. My idea is that if it gets popular enough to be challenged in court, and gets rejected for some reason, that will bring wider attention to this issue of people being unable to dedicate things to the public domain (in certain countries), which may then being people to ask *why* people want to dedicate things to the public domain, which may _then_ bring people to think about copyright itself. Maybe this will change the status quo for the better, or maybe for the worse. Maybe it'll make it harder for companies to use or contribute to rustyline-async :shrug:. Who knows! But I want to give it a try, because if people don't try to change the world, the world won't change.
